function newNode = createNode(nodeName)
    newNode = struct("Name", nodeName, "Connections", [], "Next", []);
end

function newConnection = createConnection(nodeName, weight)
    newConnection = struct("NodeTo", nodeName, "Weight", weight, "Next", []);
end

function list = add_node(list, node)
    % list struct, node struct

    if isempty(list)
        list = node;
    else
        node.Next = list; 
        list = node;
    end
end

function list = add_connection(list, fromNode, toNode, weight)

    if isempty(list)
        return
    end

    if list.Name == fromNode
        conn = createConnection(toNode, weight);

        if isempty(list.Connections)
            list.Connections = conn;
        else
            conn.Next = list.Connections;
            list.Connections = conn;
        end

    else
        list.Next = add_connection(list.Next, fromNode, toNode, weight);
    end

end

nodes = ["Marshgate", ...
         "One Pool Street", ...
         "Itsu", ...
         "Waitrose", ...
         "McDonald's", ...
         "Caffè Nero", ...
         "Greggs", ...
         "P1", ...
         "P2", ...
         "P3", ...
         "P4", ...
         "P5", ...
         "P6", ...
         "P7", ...
         "P8", ...
         "P9", ...
         "P10"];

Connections = ["Marshgate", "P1", 1, ...
               "P1", "One Pool Street", 1, ...
               "One Pool Street", "P2", 1, ...
               "One Pool Street", "P3", 1, ...
               "One Pool Street", "P4", 1, ...
               "Itsu", "P2", 1, ...
               "Itsu", "P3", 1, ...
               "Itsu", "P5", 1, ...
               "P4", "P6", 1, ...
               "P5", "P6", 1, ...
               "P5", "P7", 1, ...
               "P9", "P6", 1, ...
               "P7", "Waitrose", 1, ...
               "P8", "Waitrose", 1, ...
               "P8", "McDonald's", 1, ...
               "P7", "McDonald's", 1, ...
               "P10", "McDonald's", 1, ...
               "P7", "Caffè Nero", 1, ...
               "P9", "Caffè Nero", 1, ...
               "P9", "Greggs", 1, ...
               "P10", "Greggs", 1];

graph = [];

for i = 1:numel(nodes)
    graph = add_node(graph, createNode(nodes(numel(nodes)-i+1)));
end

for i = 1:3:numel(Connections)
    fromNode = Connections(i);
    toNode   = Connections(i+1);
    weight   = Connections(i+2);

    graph = add_connection(graph, fromNode, toNode, weight);
    graph = add_connection(graph, toNode, fromNode, weight);
end

